export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const FULL_SCREEN = 'FULL_SCREEN';
export const FULL_SCREEN_EXIT = 'FULL_SCREEN_EXIT';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const SAVE_NODE = 'SAVE_NODE';
export const SAVE_LINK = 'SAVE_LINK';
export const CHANGE_RESULTS = 'CHANGE_RESULTS';
export const CHANGE_SELECTED = 'CHANGE_SELECTED';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';
export const ADD_NODES = 'ADD_NODES';
export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';
export const ADD_LINKS = 'ADD_LINKS';
export const SAVE_WORKFLOW = 'SAVE_WORKFLOW';
export const CLOSE_WORKFLOW_DIALOG = 'CLOSE_WORKFLOW_DIALOG';
export const CLOSE_MODEL_DIALOG = 'CLOSE_MODEL_DIALOG';
export const CLOSE_COLLECTION_DIALOG = 'CLOSE_COLLECTION_DIALOG';
export const GET_MENU_ITEMS = 'GET_MENU_ITEMS';


